Category.create(name: "Perfumes")
Category.create(name: "Libros")
Category.create(name: "Tecnologia")
Category.create(name: "Electrodomesticos")
Category.create(name: "Aseo")
Category.create(name: "Juguetes")
Category.create(name: "Ropa")
Category.create(name: "Oficina")
Category.create(name: "Mascotas")

Product.create(name: "bicileta", price: 123456, category_ids: [1,2,3,4])
Product.create(name: "pc", price: 123, category_ids: [5,6,7,8])